### ISSUE TITLE
MQTT: enable not saved and empty host crashes

### ISSUE THREAD

**Issue by nottledim** [ruaraidheu/CamViewer#1] opened 2018-09-06 09:19 UTC
**Describe the bug**
If I clear the host field in mqtt local settings and close the dialog the program stops.
The state of enable checkbox is not respected when program starts.

**To Reproduce**

**Expected behavior**
No crashes and respect for settings.

**Screenshots**
picture of camviewer after crash.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  linux
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] 68

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] nexus 5x
 - OS: [e.g. iOS8.1]  android 8.1
 - Browser [e.g. stock browser, safari]  firefox

**Additional context**

**Comment by ruaraidheu** [comment] 2018-09-06 18:47
Can't Reproduce on Windows

Has the check box been set in the config file?

is there a crash window on crash, can you attach the stack trace if so?

**Comment by ruaraidheu** [comment] 2018-09-07 00:30
settings aren't being saved in 2.1.4 on mono due to address being overwritten when setting default address

**Comment by ruaraidheu** [comment] 2018-09-07 00:31
this should be fixed in 2.1.5

**Closed as completed by ruaraidheu** 2018-09-07 00:31 UTC
Labels: bug, Mono Only
